### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED when false

### ISSUE THREAD

**Issue by margeson** [StackStorm-Exchange/stackstorm-vsphere#21]
SSL verifiy is set to false; however, its attempting to use SSL. 

Am I doing something wrong here? 

```
root@stackstorm:/opt/stackstorm/packs# cat ../configs/vsphere.yaml 
---
ssl_verify: false
vsphere:
  default:
    host: "vcenter.domain.local"
    port: 443
    user: "stackstorm@vsphere.local"
    passwd: "bla"
root@stackstorm:/opt/stackstorm/packs# python --version
Python 2.7.12
root@stackstorm:/opt/stackstorm/packs# dpkg -s python-pyvmomi
Package: python-pyvmomi
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 1155
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 5.5.0-2014.1.1-3
Depends: python-requests, python-six, python:any (<< 2.8), python:any (>= 2.7.5-5~)
Pre-Depends: dpkg (>= 1.15.6~)
Suggests: python-pyvmomi-doc
Description: VMware vSphere Python SDK - Python 2.x
 pyVmomi is the Python SDK for the VMware vSphere API that allows you to
 automate actions on VMware ESX, ESXi, and vCenter servers.
 .
 This package contains the Python 2.x module.
Original-Maintainer: PKG OpenStack <openstack-devel@lists.alioth.debian.org>
Homepage: https://github.com/vmware/pyvmomi
root@stackstorm:/opt/stackstorm/packs# st2 run vsphere.vm_hw_basic_build vm_nic_netname="VM Network LAN" vm_name="test" vm_dccluster="DC"
.................
id: 595e73b002ebd5407daf3597
action.ref: vsphere.vm_hw_basic_build
parameters: 
  vm_dccluster: DC
  vm_name: test
  vm_nic_netname: VM
status: failed
error: Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 259, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 155, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/vsphere/actions/vm_hw_barebones_create.py", line 48, in run
    self.establish_connection(vsphere)
  File "/opt/stackstorm/packs/vsphere/actions/vmwarelib/actions.py", line 55, in establish_connection
    self.si = self._connect(vsphere)
  File "/opt/stackstorm/packs/vsphere/actions/vmwarelib/actions.py", line 77, in _connect
    raise Exception(e)
Exception: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

traceback: None
failed_on: barebones_build
start_timestamp: 2017-07-06T17:30:24.474665Z
end_timestamp: 2017-07-06T17:30:57.839391Z
+--------------------------+---------------------+-----------------+--------------------------------+-------------------------------+
| id                       | status              | task            | action                         | start_timestamp               |
+--------------------------+---------------------+-----------------+--------------------------------+-------------------------------+
| 595e73b002ebd5407daf359a | failed (2s elapsed) | barebones_build | vsphere.vm_hw_barebones_create | Thu, 06 Jul 2017 17:30:24 UTC |
+--------------------------+---------------------+-----------------+--------------------------------+------------------------
```

**Comment by LindsayHill** [comment]
@margeson From a quick skim, config looks correct. There was an issue with ST2 2.3.0, related to boolean values and defaults. I'm not certain, but it may be related to your issue. If you're running 2.3.0, can you upgrade st2 to 2.3.1? Packages were released to stable today.

**Comment by paul-mulvihill** [comment]
The setup looks right to me and matches what I have. My dev vsphere don't do ssl.

**Comment by LindsayHill** [comment]
I've just done a quick test with my lab system, and it doesn't have any problems. I have self-signed certs, and if I set `ssl_verify: false`, it seems to be OK.

@margeson can you confirm which ST2 version you're using, and that you ran `st2ctl reload --register-configs` after making changes to `vsphere.yaml` ?

**Comment by nmaludy** [comment]
I just tested with my vSphere that uses self-signed certs and haven't had any problems

**Comment by LindsayHill** [comment]
Had forgotten about this. Might as well close it, since it has been tested working by multiple people
