### ISSUE TITLE
Unhandled exception when retrieving tags

### ISSUE THREAD

**Issue by ndrolf** [StackStorm-Exchange/stackstorm-vsphere#89]
Following a vcenter upgrade to 7.0u3 last week, we are now seeing the exact same error as shown in #83 

The upgrade seems to have changed or reverted something that no longer allows the action to run properly.

id: ID
action.ref: vsphere.tag_attach_or_create
context.user: USER
parameters: 
  category_name: TAG
  object_id: ID
  object_type: VirtualMachine
  tag_name: TAG_INFO
status: failed (1s elapsed)
start_timestamp: Fri, 11 Mar 2022 16:30:53 UTC
end_timestamp: Fri, 11 Mar 2022 16:30:54 UTC
log: 
  - status: requested
    timestamp: '2022-03-11T16:30:53.210000Z'
  - status: scheduled
    timestamp: '2022-03-11T16:30:53.368000Z'
  - status: running
    timestamp: '2022-03-11T16:30:53.444000Z'
  - status: failed
    timestamp: '2022-03-11T16:30:54.624000Z'
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.6/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/vsphere/actions/tag_attach_or_create.py", line 39, in run
    self.connect_rest(kwargs.get("vsphere"))
  File "/opt/stackstorm/packs/vsphere/actions/vmwarelib/actions.py", line 118, in connect_rest
    self.tagging.login()
  File "/opt/stackstorm/packs/vsphere/actions/vmwarelib/tagging.py", line 131, in login
    return dict(response.cookies)
  File "/opt/stackstorm/virtualenvs/vsphere/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/opt/stackstorm/virtualenvs/vsphere/lib/python3.6/site-packages/requests/cookies.py", line 394, in _find_no_duplicates
    raise CookieConflictError('There are multiple cookies with name, %r' % (name))
requests.cookies.CookieConflictError: There are multiple cookies with name, 'vmware-api-session-id'
"
  stdout: ''

**Comment by ndrolf** [comment]
Issue is being worked on in #88
